version: "3.7"

services:
  redis:
    image: redis:5.0.7
    hostname: redis
    container_name: redis
    networks:
      - logmonnet
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:4.0.1
    hostname: neo4j
    container_name: neo4j
    networks:
      - logmonnet
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_memory_heap_initial__size=1024m
      - NEO4J_dbms_memory_heap_max__size=1024m
      - NEO4J_dbms_memory_pagecache_size=256m

  mongodb:
    image: mongo:4.2.3-bionic
    hostname: mongodb
    container_name: mongodb
    networks:
      - logmonnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    hostname: elasticsearch
    container_name: elasticsearchdb
    networks:
      - logmonnet
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    hostname: kibana-ui
    container_name: kibana-ui
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      ES_JAVA_OPTS: "-Xms1g -Xmx2g"
    networks:
      - logmonnet
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

networks:
  logmonnet:
    driver: "bridge"
